version: "3.9"
services:
  app:
    build:
      context: .
      dockerfile: ./docker/php/Dockerfile
    volumes:
      - ./src/:/var/www/html/
    ports:
      - 8080:80
    environment:
      - DB_CONNECTION=mysql
      - DB_HOST=db
      - DB_PORT=3306
      - DB_DATABASE=masher
      - DB_USERNAME=masher
      - DB_PASSWORD=masher_password

  db:
    image: mysql:5.7
    ports:
      - 3306:3306
    volumes:
      -  db_data:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=masher
      - MYSQL_USER=masher
      - MYSQL_PASSWORD=masher_password
      - MYSQL_ROOT_PASSWORD=root
volumes:
  db_data:
